# DataFrames

DataFrame é o elemeto mais importante dos Pandas e são diretamente inspirados pela linguagem de programação R. Podemos pensar em um DataFrame como um monte de objetos da série juntos para compartilhar o mesmo índice. Vamos usar Pandas para explorar esse tópico!

In [5]:
pip install pandas

Requirement already satisfied: pandas in c:\programdata\anaconda3\lib\site-packages (0.24.2)
Requirement already satisfied: numpy>=1.12.0 in c:\programdata\anaconda3\lib\site-packages (from pandas) (1.16.4)
Requirement already satisfied: python-dateutil>=2.5.0 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2.8.0)
Requirement already satisfied: pytz>=2011k in c:\programdata\anaconda3\lib\site-packages (from pandas) (2019.1)
Requirement already satisfied: six>=1.5 in c:\programdata\anaconda3\lib\site-packages (from python-dateutil>=2.5.0->pandas) (1.12.0)
Note: you may need to restart the kernel to use updated packages.

In [6]:
conda install pandas

Collecting package metadata (current_repodata.json): ...working... done
Solving environment: ...working... done

# All requested packages already installed.


Note: you may need to restart the kernel to use updated packages.

In [8]:
import pandas as pd
import numpy as np

In [4]:
from numpy.random import randn
np.random.seed(101)

In [5]:
df = pd.DataFrame(randn(5,4),index='A B C D E'.split(),columns='W X Y Z'.split())

In [6]:
df

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

## Seleção e indexação

Vamos aprender os vários métodos para pegar dados de um DataFrame

In [7]:
df['W']

A    2.706850
B    0.651118
C   -2.018168
D    0.188695
E    0.190794
Name: W, dtype: float64

In [8]:
# Passando uma lista com nomes das colunas
df[['W','Z']]

          W         Z
A  2.706850  0.503826
B  0.651118  0.605965
C -2.018168 -0.589001
D  0.188695  0.955057
E  0.190794  0.683509

In [9]:
df.W

A    2.706850
B    0.651118
C   -2.018168
D    0.188695
E    0.190794
Name: W, dtype: float64

In [10]:
df.Z

A    0.503826
B    0.605965
C   -0.589001
D    0.955057
E    0.683509
Name: Z, dtype: float64

As colunas dos DataFrames são Series

In [11]:
type(df['W'])

pandas.core.series.Series

** Criando uma coluna: **

In [12]:
df['new'] = df['W'] + df['Y']

In [13]:
df

          W         X         Y         Z       new
A  2.706850  0.628133  0.907969  0.503826  3.614819
B  0.651118 -0.319318 -0.848077  0.605965 -0.196959
C -2.018168  0.740122  0.528813 -0.589001 -1.489355
D  0.188695 -0.758872 -0.933237  0.955057 -0.744542
E  0.190794  1.978757  2.605967  0.683509  2.796762

**Removendo colunas**

In [14]:
df.drop('new',axis=1)

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [15]:
# Porém, tal exclusão só ocorrerá se especificada no parâmetro inplace
df

          W         X         Y         Z       new
A  2.706850  0.628133  0.907969  0.503826  3.614819
B  0.651118 -0.319318 -0.848077  0.605965 -0.196959
C -2.018168  0.740122  0.528813 -0.589001 -1.489355
D  0.188695 -0.758872 -0.933237  0.955057 -0.744542
E  0.190794  1.978757  2.605967  0.683509  2.796762

In [16]:
help(df.drop)

Help on method drop in module pandas.core.frame:

drop(labels=None, axis=0, index=None, columns=None, level=None, inplace=False, errors='raise') method of pandas.core.frame.DataFrame instance
    Drop specified labels from rows or columns.

    Remove rows or columns by specifying label names and corresponding
    axis, or by specifying directly index or column names. When using a
    multi-index, labels on different levels can be removed by specifying
    the level.

    Parameters
    ----------
    labels : single label or list-like
        Index or column labels to drop.
    axis : {0 or 'index', 1 or 'columns'}, default 0
        Whether to drop labels from the index (0 or 'index') or
        columns (1 or 'columns').
    index, columns : single label or list-like
        Alternative to specifying axis (``labels, axis=1``
        is equivalent to ``columns=labels``).

        .. versionadded:: 0.21.0
    level : int or level name, optional
        For MultiIndex, level from which the labels will be removed.
    inplace : bool, default False
        If True, do operation inplace and return None.
    errors : {'ignore', 'raise'}, default 'raise'
        If 'ignore', suppress error and only existing labels are
        dropped.

    Returns
    -------
    dropped : pandas.DataFrame

    Raises
    ------
    KeyError
        If none of the labels are found in the selected axis

    See Also
    --------
    DataFrame.loc : Label-location based indexer for selection by label.
    DataFrame.dropna : Return DataFrame with labels on given axis omitted
        where (all or any) data are missing.
    DataFrame.drop_duplicates : Return DataFrame with duplicate rows
        removed, optionally only considering certain columns.
    Series.drop : Return Series with specified index labels removed.

    Examples
    --------
    >>> df = pd.DataFrame(np.arange(12).reshape(3,4),
    ...                   columns=['A', 'B', 'C', 'D'])
    >>> df
       A  B   C   D
    0  0  1   2   3
    1  4  5   6   7
    2  8  9  10  11

    Drop columns

    >>> df.drop(['B', 'C'], axis=1)
       A   D
    0  0   3
    1  4   7
    2  8  11

    >>> df.drop(columns=['B', 'C'])
       A   D
    0  0   3
    1  4   7
    2  8  11

    Drop a row by index

    >>> df.drop([0, 1])
       A  B   C   D
    2  8  9  10  11

    Drop columns and/or rows of MultiIndex DataFrame

    >>> midx = pd.MultiIndex(levels=[['lama', 'cow', 'falcon'],
    ...                              ['speed', 'weight', 'length']],
    ...                      codes=[[0, 0, 0, 1, 1, 1, 2, 2, 2],
    ...                             [0, 1, 2, 0, 1, 2, 0, 1, 2]])
    >>> df = pd.DataFrame(index=midx, columns=['big', 'small'],
    ...                   data=[[45, 30], [200, 100], [1.5, 1], [30, 20],
    ...                         [250, 150], [1.5, 0.8], [320, 250],
    ...                         [1, 0.8], [0.3,0.2]])
    >>> df
                    big     small
    lama    speed   45.0    30.0
            weight  200.0   100.0
            length  1.5     1.0
    cow     speed   30.0    20.0
            weight  250.0   150.0
            length  1.5     0.8
    falcon  speed   320.0   250.0
            weight  1.0     0.8
            length  0.3     0.2

    >>> df.drop(index='cow', columns='small')
                    big
    lama    speed   45.0
            weight  200.0
            length  1.5
    falcon  speed   320.0
            weight  1.0
            length  0.3

    >>> df.drop(index='length', level=1)
                    big     small
    lama    speed   45.0    30.0
            weight  200.0   100.0
    cow     speed   30.0    20.0
            weight  250.0   150.0
    falcon  speed   320.0   250.0
            weight  1.0     0.8

In [17]:
df.drop('new',axis=1,inplace=True)

In [18]:
df

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

Também podemos deletar colunas desta forma:

In [19]:
df.drop('E',axis=0)

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057

In [20]:
# dropando duas linhas considerando que as linhas são a lista ['D','E']
df.drop('D E'.split(),axis=0)

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001

In [21]:
df

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

**Selecionando linhas:**

In [22]:
df.loc['A']

W    2.706850
X    0.628133
Y    0.907969
Z    0.503826
Name: A, dtype: float64

Ou selecione com base na posição em vez do rótulo

In [23]:
# seleciona linha 2
df.iloc[2]

W   -2.018168
X    0.740122
Y    0.528813
Z   -0.589001
Name: C, dtype: float64

**Selecionando o subconjunto de linhas e colunas**

In [24]:
df.loc['B','Y']

-0.8480769834036315

In [25]:
df.loc[['A','B'],['W','Y']]

          W         Y
A  2.706850  0.907969
B  0.651118 -0.848077

### Seleção condicional

Uma característica importante dos pandas é a seleção condicional usando notação de colchetes, muito semelhante ao numpy:

In [26]:
df

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [27]:
df>0

       W      X      Y      Z
A   True   True   True   True
B   True  False  False   True
C  False   True   True  False
D   True  False  False   True
E   True   True   True   True

In [28]:
# importante e muito utilizado
df[df>0]

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118       NaN       NaN  0.605965
C       NaN  0.740122  0.528813       NaN
D  0.188695       NaN       NaN  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [29]:
df['W']>0

A     True
B     True
C    False
D     True
E     True
Name: W, dtype: bool

In [30]:
df[df['W']>0]

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [31]:
df

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [32]:
df[df['W']>0]['Y']

A    0.907969
B   -0.848077
D   -0.933237
E    2.605967
Name: Y, dtype: float64

In [33]:
df[df['W']>0][['Y','X']]

          Y         X
A  0.907969  0.628133
B -0.848077 -0.319318
D -0.933237 -0.758872
E  2.605967  1.978757

Para duas condições, você pode usar | e & com parênteses:

In [34]:
df[(df['W']>0) & (df['Y'] > 1)]

          W         X         Y         Z
E  0.190794  1.978757  2.605967  0.683509

## Mais Detalhes do Índice

Vamos discutir mais alguns recursos de indexação, incluindo resetar o índice ou configurá-lo de outra forma. Também falaremos sobre hierarquia de índice!

In [35]:
df

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [36]:
# Redefinir para o padrão 0,1 ... n índice
df.reset_index()

  index         W         X         Y         Z
0     A  2.706850  0.628133  0.907969  0.503826
1     B  0.651118 -0.319318 -0.848077  0.605965
2     C -2.018168  0.740122  0.528813 -0.589001
3     D  0.188695 -0.758872 -0.933237  0.955057
4     E  0.190794  1.978757  2.605967  0.683509

In [37]:
novoind = 'CA NY WY OR CO'.split()
novoind

['CA', 'NY', 'WY', 'OR', 'CO']

In [38]:
df['Estados'] = novoind

In [39]:
df

          W         X         Y         Z Estados
A  2.706850  0.628133  0.907969  0.503826      CA
B  0.651118 -0.319318 -0.848077  0.605965      NY
C -2.018168  0.740122  0.528813 -0.589001      WY
D  0.188695 -0.758872 -0.933237  0.955057      OR
E  0.190794  1.978757  2.605967  0.683509      CO

In [40]:
df.set_index('Estados')

                W         X         Y         Z
Estados
CA       2.706850  0.628133  0.907969  0.503826
NY       0.651118 -0.319318 -0.848077  0.605965
WY      -2.018168  0.740122  0.528813 -0.589001
OR       0.188695 -0.758872 -0.933237  0.955057
CO       0.190794  1.978757  2.605967  0.683509

In [41]:
df

          W         X         Y         Z Estados
A  2.706850  0.628133  0.907969  0.503826      CA
B  0.651118 -0.319318 -0.848077  0.605965      NY
C -2.018168  0.740122  0.528813 -0.589001      WY
D  0.188695 -0.758872 -0.933237  0.955057      OR
E  0.190794  1.978757  2.605967  0.683509      CO

In [42]:
#inplace será para atualizar a mudança em df
df.set_index('Estados',inplace=True)

In [43]:
df

                W         X         Y         Z
Estados
CA       2.706850  0.628133  0.907969  0.503826
NY       0.651118 -0.319318 -0.848077  0.605965
WY      -2.018168  0.740122  0.528813 -0.589001
OR       0.188695 -0.758872 -0.933237  0.955057
CO       0.190794  1.978757  2.605967  0.683509

## Hierarquia de índices e índices múltiplos
 
Vamos examinar como trabalhar com o Multi-Index, primeiro criaremos um exemplo rápido de como seria um DataFrame Multi-Indexado:

In [44]:
# Níveis de Índice
outside = ['G1','G1','G1','G2','G2','G2']
inside = [1,2,3,1,2,3]
hier_index = list(zip(outside,inside))
hier_index

[('G1', 1), ('G1', 2), ('G1', 3), ('G2', 1), ('G2', 2), ('G2', 3)]

In [45]:
help(pd.MultiIndex)

Help on class MultiIndex in module pandas.core.indexes.multi:

class MultiIndex(pandas.core.indexes.base.Index)
 |  MultiIndex(levels=None, codes=None, sortorder=None, names=None, dtype=None, copy=False, name=None, verify_integrity=True, _set_identity=True)
 |
 |  A multi-level, or hierarchical, index object for pandas objects.
 |
 |  Parameters
 |  ----------
 |  levels : sequence of arrays
 |      The unique labels for each level.
 |  codes : sequence of arrays
 |      Integers for each level designating which label at each location.
 |
 |      .. versionadded:: 0.24.0
 |  labels : sequence of arrays
 |      Integers for each level designating which label at each location.
 |
 |      .. deprecated:: 0.24.0
 |          Use ``codes`` instead
 |  sortorder : optional int
 |      Level of sortedness (must be lexicographically sorted by that
 |      level).
 |  names : optional sequence of objects
 |      Names for each of the index levels. (name is accepted for compat).
 |  copy : bool, default False
 |      Copy the meta-data.
 |  verify_integrity : bool, default True
 |      Check that the levels/codes are consistent and valid.
 |
 |  Attributes
 |  ----------
 |  names
 |  levels
 |  codes
 |  nlevels
 |  levshape
 |
 |  Methods
 |  -------
 |  from_arrays
 |  from_tuples
 |  from_product
 |  from_frame
 |  set_levels
 |  set_codes
 |  to_frame
 |  to_flat_index
 |  is_lexsorted
 |  sortlevel
 |  droplevel
 |  swaplevel
 |  reorder_levels
 |  remove_unused_levels
 |
 |  See Also
 |  --------
 |  MultiIndex.from_arrays  : Convert list of arrays to MultiIndex.
 |  MultiIndex.from_product : Create a MultiIndex from the cartesian product
 |                            of iterables.
 |  MultiIndex.from_tuples  : Convert list of tuples to a MultiIndex.
 |  MultiIndex.from_frame   : Make a MultiIndex from a DataFrame.
 |  Index : The base pandas Index type.
 |
 |  Examples
 |  ---------
 |  A new ``MultiIndex`` is typically constructed using one of the helper
 |  methods :meth:`MultiIndex.from_arrays`, :meth:`MultiIndex.from_product`
 |  and :meth:`MultiIndex.from_tuples`. For example (using ``.from_arrays``):
 |
 |  >>> arrays = [[1, 1, 2, 2], ['red', 'blue', 'red', 'blue']]
 |  >>> pd.MultiIndex.from_arrays(arrays, names=('number', 'color'))
 |  MultiIndex(levels=[[1, 2], ['blue', 'red']],
 |             codes=[[0, 0, 1, 1], [1, 0, 1, 0]],
 |             names=['number', 'color'])
 |
 |  See further examples for how to construct a MultiIndex in the doc strings
 |  of the mentioned helper methods.
 |
 |  Notes
 |  -----
 |  See the `user guide
 |  <http://pandas.pydata.org/pandas-docs/stable/advanced.html>`_ for more.
 |
 |  Method resolution order:
 |      MultiIndex
 |      pandas.core.indexes.base.Index
 |      pandas.core.base.IndexOpsMixin
 |      pandas.core.base.PandasObject
 |      pandas.core.base.StringMixin
 |      pandas.core.accessor.DirNamesMixin
 |      builtins.object
 |
 |  Methods defined here:
 |
 |  __abs__(self, other=None)
 |
 |  __add__(self, other=None)
 |
 |  __array__(self, dtype=None)
 |      the array interface, return my values
 |
 |  __contains__(self, key)
 |      Return a boolean indicating whether the provided key is in the index.
 |
 |      Parameters
 |      ----------
 |      key : label
 |          The key to check if it is present in the index.
 |
 |      Returns
 |      -------
 |      bool
 |          Whether the key search is in the index.
 |
 |      See Also
 |      --------
 |      Index.isin : Returns an ndarray of boolean dtype indicating whether the
 |          list-like key is in the index.
 |
 |      Examples
 |      --------
 |      >>> idx = pd.Index([1, 2, 3, 4])
 |      >>> idx
 |      Int64Index([1, 2, 3, 4], dtype='int64')
 |
 |      >>> idx.contains(2)
 |      True
 |      >>> idx.contains(6)
 |      False
 |
 |      This is equivalent to:
 |
 |      >>> 2 in idx
 |      True
 |      >>> 6 in idx
 |      False
 |
 |  __divmod__(self, other=None)
 |
 |  __floordiv__(self, other=None)
 |
 |  __getitem__(self, key)
 |      Override numpy.ndarray's __getitem__ method to work as desired.
 |
 |      This function adds lists and Series as valid boolean indexers
 |      (ndarrays only supports ndarray with dtype=bool).
 |
 |      If resulting ndim != 1, plain ndarray is returned instead of
 |      corresponding `Index` subclass.
 |
 |  __getslice__(self, i, j)
 |
 |  __iadd__(self, other=None)
 |
 |  __inv__(self, other=None)
 |
 |  __isub__(self, other=None)
 |
 |  __len__(self)
 |      Return the length of the Index.
 |
 |  __mod__(self, other=None)
 |
 |  __mul__(self, other=None)
 |
 |  __neg__(self, other=None)
 |
 |  __pos__(self, other=None)
 |
 |  __pow__(self, other=None)
 |
 |  __radd__(self, other=None)
 |
 |  __reduce__(self)
 |      Necessary for making this object picklable
 |
 |  __rfloordiv__(self, other=None)
 |
 |  __rmul__(self, other=None)
 |
 |  __rpow__(self, other=None)
 |
 |  __rsub__(self, other=None)
 |
 |  __rtruediv__(self, other=None)
 |
 |  __setstate__(self, state)
 |      Necessary for making this object picklable
 |
 |  __sub__(self, other=None)
 |
 |  __truediv__(self, other=None)
 |
 |  all(self, other=None)
 |
 |  any(self, other=None)
 |
 |  append(self, other)
 |      Append a collection of Index options together
 |
 |      Parameters
 |      ----------
 |      other : Index or list/tuple of indices
 |
 |      Returns
 |      -------
 |      appended : Index
 |
 |  argsort(self, *args, **kwargs)
 |      Return the integer indices that would sort the index.
 |
 |      Parameters
 |      ----------
 |      *args
 |          Passed to `numpy.ndarray.argsort`.
 |      **kwargs
 |          Passed to `numpy.ndarray.argsort`.
 |
 |      Returns
 |      -------
 |      numpy.ndarray
 |          Integer indices that would sort the index if used as
 |          an indexer.
 |
 |      See Also
 |      --------
 |      numpy.argsort : Similar method for NumPy arrays.
 |      Index.sort_values : Return sorted copy of Index.
 |
 |      Examples
 |      --------
 |      >>> idx = pd.Index(['b', 'a', 'd', 'c'])
 |      >>> idx
 |      Index(['b', 'a', 'd', 'c'], dtype='object')
 |
 |      >>> order = idx.argsort()
 |      >>> order
 |      array([1, 0, 3, 2])
 |
 |      >>> idx[order]
 |      Index(['a', 'b', 'c', 'd'], dtype='object')
 |
 |  astype(self, dtype, copy=True)
 |      Create an Index with values cast to dtypes. The class of a new Index
 |      is determined by dtype. When conversion is impossible, a ValueError
 |      exception is raised.
 |
 |      Parameters
 |      ----------
 |      dtype : numpy dtype or pandas type
 |          Note that any signed integer `dtype` is treated as ``'int64'``,
 |          and any unsigned integer `dtype` is treated as ``'uint64'``,
 |          regardless of the size.
 |      copy : bool, default True
 |          By default, astype always returns a newly allocated object.
 |          If copy is set to False and internal requirements on dtype are
 |          satisfied, the original data is used to create a new Index
 |          or the original Index is returned.
 |
 |          .. versionadded:: 0.19.0
 |
 |  contains = __contains__(self, key)
 |
 |  copy(self, names=None, dtype=None, levels=None, codes=None, deep=False, _set_identity=False, **kwargs)
 |      Make a copy of this object. Names, dtype, levels and codes can be
 |      passed and will be set on new copy.
 |
 |      Parameters
 |      ----------
 |      names : sequence, optional
 |      dtype : numpy dtype or pandas type, optional
 |      levels : sequence, optional
 |      codes : sequence, optional
 |
 |      Returns
 |      -------
 |      copy : MultiIndex
 |
 |      Notes
 |      -----
 |      In most cases, there should be no functional difference from using
 |      ``deep``, but if ``deep`` is passed it will attempt to deepcopy.
 |      This could be potentially expensive on large MultiIndex objects.
 |
 |  delete(self, loc)
 |      Make new index with passed location deleted
 |
 |      Returns
 |      -------
 |      new_index : MultiIndex
 |
 |  difference(self, other, sort=None)
 |      Compute set difference of two MultiIndex objects
 |
 |      Parameters
 |      ----------
 |      other : MultiIndex
 |      sort : False or None, default None
 |          Sort the resulting MultiIndex if possible
 |
 |          .. versionadded:: 0.24.0
 |
 |          .. versionchanged:: 0.24.1
 |
 |             Changed the default value from ``True`` to ``None``
 |             (without change in behaviour).
 |
 |      Returns
 |      -------
 |      diff : MultiIndex
 |
 |  drop(self, codes, level=None, errors='raise')
 |      Make new MultiIndex with passed list of codes deleted
 |
 |      Parameters
 |      ----------
 |      codes : array-like
 |          Must be a list of tuples
 |      level : int or level name, default None
 |
 |      Returns
 |      -------
 |      dropped : MultiIndex
 |
 |  dropna(self, how='any')
 |      Return Index without NA/NaN values
 |
 |      Parameters
 |      ----------
 |      how :  {'any', 'all'}, default 'any'
 |          If the Index is a MultiIndex, drop the value when any or all levels
 |          are NaN.
 |
 |      Returns
 |      -------
 |      valid : Index
 |
 |  duplicated(self, keep='first')
 |      Indicate duplicate index values.
 |
 |      Duplicated values are indicated as ``True`` values in the resulting
 |      array. Either all duplicates, all except the first, or all except the
 |      last occurrence of duplicates can be indicated.
 |
 |      Parameters
 |      ----------
 |      keep : {'first', 'last', False}, default 'first'
 |          The value or values in a set of duplicates to mark as missing.
 |
 |          - 'first' : Mark duplicates as ``True`` except for the first
 |            occurrence.
 |          - 'last' : Mark duplicates as ``True`` except for the last
 |            occurrence.
 |          - ``False`` : Mark all duplicates as ``True``.
 |
 |      Returns
 |      -------
 |      numpy.ndarray
 |
 |      See Also
 |      --------
 |      pandas.Series.duplicated : Equivalent method on pandas.Series.
 |      pandas.DataFrame.duplicated : Equivalent method on pandas.DataFrame.
 |      pandas.Index.drop_duplicates : Remove duplicate values from Index.
 |
 |      Examples
 |      --------
 |      By default, for each set of duplicated values, the first occurrence is
 |      set to False and all others to True:
 |
 |      >>> idx = pd.Index(['lama', 'cow', 'lama', 'beetle', 'lama'])
 |      >>> idx.duplicated()
 |      array([False, False,  True, False,  True])
 |
 |      which is equivalent to
 |
 |      >>> idx.duplicated(keep='first')
 |      array([False, False,  True, False,  True])
 |
 |      By using 'last', the last occurrence of each set of duplicated values
 |      is set on False and all others on True:
 |
 |      >>> idx.duplicated(keep='last')
 |      array([ True, False,  True, False, False])
 |
 |      By setting keep on ``False``, all duplicates are True:
 |
 |      >>> idx.duplicated(keep=False)
 |      array([ True, False,  True, False,  True])
 |
 |  equal_levels(self, other)
 |      Return True if the levels of both MultiIndex objects are the same
 |
 |  equals(self, other)
 |      Determines if two MultiIndex objects have the same labeling information
 |      (the levels themselves do not necessarily have to be the same)
 |
 |      See Also
 |      --------
 |      equal_levels
 |
 |  fillna(self, value=None, downcast=None)
 |      fillna is not implemented for MultiIndex
 |
 |  format(self, space=2, sparsify=None, adjoin=True, names=False, na_rep=None, formatter=None)
 |      Render a string representation of the Index.
 |
 |  get_indexer(self, target, method=None, limit=None, tolerance=None)
 |      Compute indexer and mask for new index given the current index. The
 |      indexer should be then used as an input to ndarray.take to align the
 |      current data to the new index.
 |
 |      Parameters
 |      ----------
 |      target : MultiIndex or list of tuples
 |      method : {None, 'pad'/'ffill', 'backfill'/'bfill', 'nearest'}, optional
 |          * default: exact matches only.
 |          * pad / ffill: find the PREVIOUS index value if no exact match.
 |          * backfill / bfill: use NEXT index value if no exact match
 |          * nearest: use the NEAREST index value if no exact match. Tied
 |            distances are broken by preferring the larger index value.
 |      limit : int, optional
 |          Maximum number of consecutive labels in ``target`` to match for
 |          inexact matches.
 |      tolerance : optional
 |          Maximum distance between original and new labels for inexact
 |          matches. The values of the index at the matching locations most
 |          satisfy the equation ``abs(index[indexer] - target) <= tolerance``.
 |
 |          Tolerance may be a scalar value, which applies the same tolerance
 |          to all values, or list-like, which applies variable tolerance per
 |          element. List-like includes list, tuple, array, Series, and must be
 |          the same size as the index and its dtype must exactly match the
 |          index's type.
 |
 |          .. versionadded:: 0.21.0 (list-like tolerance)
 |
 |      Returns
 |      -------
 |      indexer : ndarray of int
 |          Integers from 0 to n - 1 indicating that the index at these
 |          positions matches the corresponding target values. Missing values
 |          in the target are marked by -1.
 |
 |      Examples
 |      --------
 |      >>> index = pd.Index(['c', 'a', 'b'])
 |      >>> index.get_indexer(['a', 'b', 'x'])
 |      array([ 1,  2, -1])
 |
 |      Notice that the return value is an array of locations in ``index``
 |      and ``x`` is marked by -1, as it is not in ``index``.
 |
 |  get_indexer_non_unique(self, target)
 |      Compute indexer and mask for new index given the current index. The
 |      indexer should be then used as an input to ndarray.take to align the
 |      current data to the new index.
 |
 |      Parameters
 |      ----------
 |      target : MultiIndex or list of tuples
 |
 |      Returns
 |      -------
 |      indexer : ndarray of int
 |          Integers from 0 to n - 1 indicating that the index at these
 |          positions matches the corresponding target values. Missing values
 |          in the target are marked by -1.
 |      missing : ndarray of int
 |          An indexer into the target of the values not found.
 |          These correspond to the -1 in the indexer array
 |
 |  get_level_values(self, level)
 |      Return vector of label values for requested level,
 |      equal to the length of the index.
 |
 |      Parameters
 |      ----------
 |      level : int or str
 |          ``level`` is either the integer position of the level in the
 |          MultiIndex, or the name of the level.
 |
 |      Returns
 |      -------
 |      values : Index
 |          ``values`` is a level of this MultiIndex converted to
 |          a single :class:`Index` (or subclass thereof).
 |
 |      Examples
 |      ---------
 |
 |      Create a MultiIndex:
 |
 |      >>> mi = pd.MultiIndex.from_arrays((list('abc'), list('def')))
 |      >>> mi.names = ['level_1', 'level_2']
 |
 |      Get level values by supplying level as either integer or name:
 |
 |      >>> mi.get_level_values(0)
 |      Index(['a', 'b', 'c'], dtype='object', name='level_1')
 |      >>> mi.get_level_values('level_2')
 |      Index(['d', 'e', 'f'], dtype='object', name='level_2')
 |
 |  get_loc(self, key, method=None)
 |      Get location for a label or a tuple of labels as an integer, slice or
 |      boolean mask.
 |
 |      Parameters
 |      ----------
 |      key : label or tuple of labels (one for each level)
 |      method : None
 |
 |      Returns
 |      -------
 |      loc : int, slice object or boolean mask
 |          If the key is past the lexsort depth, the return may be a
 |          boolean mask array, otherwise it is always a slice or int.
 |
 |      Examples
 |      ---------
 |      >>> mi = pd.MultiIndex.from_arrays([list('abb'), list('def')])
 |
 |      >>> mi.get_loc('b')
 |      slice(1, 3, None)
 |
 |      >>> mi.get_loc(('b', 'e'))
 |      1
 |
 |      Notes
 |      ------
 |      The key cannot be a slice, list of same-level labels, a boolean mask,
 |      or a sequence of such. If you want to use those, use
 |      :meth:`MultiIndex.get_locs` instead.
 |
 |      See Also
 |      --------
 |      Index.get_loc : The get_loc method for (single-level) index.
 |      MultiIndex.slice_locs : Get slice location given start label(s) and
 |                              end label(s).
 |      MultiIndex.get_locs : Get location for a label/slice/list/mask or a
 |                            sequence of such.
 |
 |  get_loc_level(self, key, level=0, drop_level=True)
 |      Get both the location for the requested label(s) and the
 |      resulting sliced index.
 |
 |      Parameters
 |      ----------
 |      key : label or sequence of labels
 |      level : int/level name or list thereof, optional
 |      drop_level : bool, default True
 |          if ``False``, the resulting index will not drop any level.
 |
 |      Returns
 |      -------
 |      loc : A 2-tuple where the elements are:
 |            Element 0: int, slice object or boolean array
 |            Element 1: The resulting sliced multiindex/index. If the key
 |            contains all levels, this will be ``None``.
 |
 |      Examples
 |      --------
 |      >>> mi = pd.MultiIndex.from_arrays([list('abb'), list('def')],
 |      ...                                names=['A', 'B'])
 |
 |      >>> mi.get_loc_level('b')
 |      (slice(1, 3, None), Index(['e', 'f'], dtype='object', name='B'))
 |
 |      >>> mi.get_loc_level('e', level='B')
 |      (array([False,  True, False], dtype=bool),
 |      Index(['b'], dtype='object', name='A'))
 |
 |      >>> mi.get_loc_level(['b', 'e'])
 |      (1, None)
 |
 |      See Also
 |      ---------
 |      MultiIndex.get_loc  : Get location for a label or a tuple of labels.
 |      MultiIndex.get_locs : Get location for a label/slice/list/mask or a
 |                            sequence of such.
 |
 |  get_locs(self, seq)
 |      Get location for a given label/slice/list/mask or a sequence of such as
 |      an array of integers.
 |
 |      Parameters
 |      ----------
 |      seq : label/slice/list/mask or a sequence of such
 |         You should use one of the above for each level.
 |         If a level should not be used, set it to ``slice(None)``.
 |
 |      Returns
 |      -------
 |      locs : array of integers suitable for passing to iloc
 |
 |      Examples
 |      ---------
 |      >>> mi = pd.MultiIndex.from_arrays([list('abb'), list('def')])
 |
 |      >>> mi.get_locs('b')
 |      array([1, 2], dtype=int64)
 |
 |      >>> mi.get_locs([slice(None), ['e', 'f']])
 |      array([1, 2], dtype=int64)
 |
 |      >>> mi.get_locs([[True, False, True], slice('e', 'f')])
 |      array([2], dtype=int64)
 |
 |      See Also
 |      --------
 |      MultiIndex.get_loc : Get location for a label or a tuple of labels.
 |      MultiIndex.slice_locs : Get slice location given start label(s) and
 |                              end label(s).
 |
 |  get_slice_bound(self, label, side, kind)
 |      Calculate slice bound that corresponds to given label.
 |
 |      Returns leftmost (one-past-the-rightmost if ``side=='right'``) position
 |      of given label.
 |
 |      Parameters
 |      ----------
 |      label : object
 |      side : {'left', 'right'}
 |      kind : {'ix', 'loc', 'getitem'}
 |
 |  get_value(self, series, key)
 |      Fast lookup of value from 1-dimensional ndarray. Only use this if you
 |      know what you're doing.
 |
 |  insert(self, loc, item)
 |      Make new MultiIndex inserting new item at location
 |
 |      Parameters
 |      ----------
 |      loc : int
 |      item : tuple

In [46]:
hier_index = pd.MultiIndex.from_tuples(hier_index)
hier_index

MultiIndex(levels=[['G1', 'G2'], [1, 2, 3]],
           codes=[[0, 0, 0, 1, 1, 1], [0, 1, 2, 0, 1, 2]])

In [47]:
hier_index

MultiIndex(levels=[['G1', 'G2'], [1, 2, 3]],
           codes=[[0, 0, 0, 1, 1, 1], [0, 1, 2, 0, 1, 2]])

In [48]:
df = pd.DataFrame(np.random.randn(6,2),index=hier_index,columns=['A','B'])
df

             A         B
G1 1  0.302665  1.693723
   2 -1.706086 -1.159119
   3 -0.134841  0.390528
G2 1  0.166905  0.184502
   2  0.807706  0.072960
   3  0.638787  0.329646

In [20]:
#Exemplo com entrada pd.MultiIndex.from_arrays
tupla_indice=(list('abc'), list('def'))
hierarquina_indices = pd.MultiIndex.from_arrays(tupla_indice)
hierarquina_indices.names = ['level_1', 'level_2']
hierarquina_indices
df_indice_array = pd.DataFrame(np.random.randn(3,2),index=hierarquina_indices,columns=['A','B'])
df_indice_array

                        A         B
level_1 level_2
a       d       -0.679774 -0.120123
b       e       -0.881018  0.085418
c       f        0.413940 -1.243340

Agora vamos mostrar como indexar isso! Para a hierarquia de índice, usamos df.loc []. Se este fosse no eixo das colunas, você usaria a notação de suporte normal df []. Chamar um nível do índice retorna um sub-dataframe:

In [50]:
df.loc['G1']

          A         B
1  0.302665  1.693723
2 -1.706086 -1.159119
3 -0.134841  0.390528

In [51]:
df.loc['G1'].loc[1]

A    0.302665
B    1.693723
Name: 1, dtype: float64

In [52]:
df.index.names

FrozenList([None, None])

In [53]:
df.index.names = ['Grupo','Número']

In [54]:
df

                     A         B
Grupo Número
G1    1       0.302665  1.693723
      2      -1.706086 -1.159119
      3      -0.134841  0.390528
G2    1       0.166905  0.184502
      2       0.807706  0.072960
      3       0.638787  0.329646

In [55]:
# pesquisar o nível dos índices
df.xs('G1')

               A         B
Número
1       0.302665  1.693723
2      -1.706086 -1.159119
3      -0.134841  0.390528

In [56]:
df.xs(['G1',1])

A    0.302665
B    1.693723
Name: (G1, 1), dtype: float64

In [57]:
df.xs(1,level='Número')

              A         B
Grupo
G1     0.302665  1.693723
G2     0.166905  0.184502